server:
  port: 8081
  servlet:
    context-path: /pt-backend

spring:
  data:
    mongodb:
      authentication-database: admin
      database: personality-test
      port: 27017
      host: localhost
  jpa:
    hibernate:
      ddl-auto: create
